spring:
  datasource:
    url: jdbc:postgresql://ep-withered-tooth-a1wrezlj-pooler.ap-southeast-1.aws.neon.tech/boodb
    username: boodb_owner
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#    session:
#      cookie:
#        same-site: none
